version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: ["python", "main.py"]
    depends_on:
      - mongodb
      - beat
      - worker
      - redis
    volumes:
      - pdf_volume:/app/diplomas
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  beat:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "worker", "beat", "-S", "celerybeatmongo.schedulers.MongoScheduler", "-l", "debug"]
    depends_on:
      - mongodb
  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "worker", "worker", "-l", "debug"]
    depends_on:
      - mongodb
    volumes:
      - pdf_volume:/app/diplomas
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  mongodb-data:
  pdf_volume:
